### ISSUE TITLE
As a user, I want to run 'zero init' command so I can initialize my new project ready for further configuration

### ISSUE THREAD

**Issue by beiercai** [commitdev/zero#118]
## Acceptance Criteria:
- Create zero.yml file with user customization
- Contains all values we prompted user to enter
- Modules github url included
- Meta info about the project
“/home/username/.zero-config” created and populated with default info

## Things to think about
- In the future, we should have a single repo contains all project specific yml configs shared across the org. 
  - OrgName/Hello-World/zero.yml
  - OrgName/Welcome/zero.yml
- Pre-populate preferences as default choices already stored in /home/username/.zero/config collected from last run of `zero init` command, such as cloud provider. In
ELK stack

**Comment by davidcheung** [comment]
### Init 
**Must have**
- [ ] prompt stack + global 
- [ ] download stack inferred modules [eks + backend + frontend]
- [ ] support downloaded module's zero-module.yml 
  - [ ] when `execute` is present, exec cmds to fetch project config
  - [ ] prompt invidivual module's params 
    - [ ] determine if global config/creds have info
    - [ ] able to pick up reasonable defaults when applicable 
    - [ ] able to not reprompt items other modules asked for
  - [ ] prompt the git repo name (zero-module's outputdir)
- [ ] dynamic template for zero.yml
  - [ ] name
  - [ ] modules 
  - [ ] params + comments + info
- [ ] create or update ~/.zero/credentials.yml  or from ~/.aws (if we do conversion will we lose comments in yml?)


**Nice to have**
- [ ] `~/.zero/config` ? gather project structure + meta (In the future, we should have a single repo contains all project specific yml configs shared across the org. )
