### ISSUE TITLE
Zero product roadmap

### ISSUE THREAD

**Issue by beiercai** [commitdev/zero#137]
Create a high-level product roadmap for Zero that is reverse-engineered from the Press Release zero-old#15

- From open source practice perspective
- From technical implementation perspective(for example, when to take package management into account. 

Beier will start interviewing technical founders from the user's perspective (features/modules they want to see)

**Comment by anubhavmishra** [comment]
I started working on it. Here is the first draft: https://docs.google.com/document/d/1sioLHwgLWm4vJrNNwMrlprCVZv8Kfmo-EGqH7uircJU/edit#
