### ISSUE TITLE
Docker only setup research

### ISSUE THREAD

**Issue by beiercai** [commitdev/zero#184]
Why? 
Our K8s based setup is more complicated and pricy (could cost $150-$200/month) than many early stage startups want, especially those who are still building out their initial product features without any real production customers, likely for the first few months. 

Ideally, we want to figure out a way to put Zero customers on a cheap and lightweight solution (Docker setup?) to begin with, while allowing them to migrate to K8s based setup easily when they start having real customers, real traffics, and can afford to pay the bigger infrastructure price that comes with K8s

This github issue is for investigating & researching a more primitive approach to setting up the infrastructure on AWS without K8s that is more lightweight, and most importantly doesn't cost much money.

While Docker is an obvious solution, it's not necessarily the best one, so feel free to investigate and suggest other possibilities. 

Objectives for this ticket
- [ ] Research a lightweight and cheap/free solution to get early-stage startups off running without K8s
- [ ] Create a high-level implementation plan for how we can make this happen, and what are the potential technical uncertainties
- [ ] Design a migration path from the simpler solution to our standard K8s based solution, so that when the customer is ready to adopt K8s, it could be as simple as a single command/button click. 
- [ ] Provide some high level effort estimate to make this happen
- [ ] All research result documented in Google Doc

**Comment by CoreyH** [comment]
I've used Azure App Service for Containers very successfully: https://azure.microsoft.com/en-us/services/app-service/containers/

You supply the Docker image and they handle almost everything else. Much, much easier to set up than K8s and affordable.

**Comment by davidcheung** [comment]
Potentially useful for the research: https://github.com/nathanpeck/awesome-ecs#infrastructure-as-code

**Comment by cjhawkins** [comment]
Research doc: https://docs.google.com/document/d/1xv3yvLRVQCeQSx735rib9A8lQxId6EDPc2gxh1-bfts/edit?usp=sharing
