### ISSUE TITLE
LX

### ISSUE THREAD

**Issue by beiercai** [commitdev/zero#185]
Write a ReadMe page in the repo to explain why we believe the AWS-EKS-Stack infrastructure is the ideal setup for most startups. 

The ReadMe writeup should contain at least the following components. Feel free to add more contents that you feel appropriate. 

- [x] Explain what the AWS-EKS-Stack setup is and how they work together (in Zero repo ReadMe)
- [x] How does the setup help startups build out a reliable, scalable, performant and secure infrastructure
- [x] Different places to have ReadMe (in Zero repo, in our core Modules repo each has two ReadMes)
- [x] high-level Architecture diagram (make sure to keep up to date, and add a link in Zero repo back to this diagram. )

**Comment by bmonkman** [comment]
Other things to think about:

- What is the high level view of our Learning Experience?
- What are all the components? 
  - Documentation on a future Zero site
  - Readme for the modules
  - Readme that gets templated into projects
  - Documentation, links, context, etc. during the initial setup of a project
  - Do we need a GUI during setup or can we have a rich enough experience with a CLI?
- How do we give users the right information at the right time?
 - Before they use Zero at all
 - During the setup
 - As they first start using their new system
 - Ongoing into the future as they become a power-user of the tools we have set up

**Comment by dtoki** [comment]
Feedback from eps: https://github.com/commitdev/zero/issues/217
