### ISSUE TITLE
Module/Ecosystem Research

### ISSUE THREAD

**Issue by beiercai** [commitdev/zero#187]
Module is a critical concept for Zero to achieve the goals of extensibility and modularity. As we are about to go beyond just simple React/Go/EKS setup, it's time to research how we can design and architect this modular system. 

Major considerations of this research

- Map out everything that Zero will have across different tech layers 
- Revisit Nomenclatures/definitions, define different layers, components (or whatever terminology that makes sense)
- How modules would interactive with each other
- How to manage module dependencies
- How to do module/package management
- How to make it possible for external module contributions and build out an open source ecosystem

**Comment by bmonkman** [comment]
Started a doc to collect thoughts while brainstorming: https://docs.google.com/document/d/1Y7kEIWgKsKKnJSBBHJC8vJd_DoJOKmhCEE7NozpUShs/edit
