### ISSUE TITLE
Create user login / registration project

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#202]

**Comment by bmonkman** [comment]
Create a frontend similar to the ory example project for Kratos: https://github.com/ory/kratos-selfservice-ui-node

Think about how to package it: 
- Container supplied by us on docker hub with code in github?
- Zero module checked in to user's github org with CI pipeline to deploy to S3/Cloudfront? 

Probably need to split this into more tickets for individual features of the frontend.

**Comment by jasondippel** [comment]
List of features ORY Kratos example provides that we will have to build out:

- [ ] Registration
- [ ] Login
- [ ] Logout
- [ ] User settings
  - [ ] Update profile
  - [ ] Change password
- [ ] Password reset
- [ ] Dashboard (shown when user is logged in)

The ORY example does contain an [error page](https://selfservice.commitzero.com/auth/login?request=bad_request) as well, but I think we can handle this a little nicer than building out a page which shows the bad response.

These features should be added to the existing [Zero Deployable Frontend](https://github.com/commitdev/zero-deployable-react-frontend) project. Exact designs will be determined in the future. For now, just build something simple.

**Comment by jasondippel** [comment]
[Branch with code changes](https://github.com/commitdev/zero-deployable-react-frontend/tree/basic_user_management)
