### ISSUE TITLE
Zero's License

### ISSUE THREAD

**Issue by dtoki** [commitdev/zero#218]

**Comment by GrooveStomp** [comment]
Need to talk with Tiff about requirements on the business side.

Resources for finding what options there are:
- https://opensource.org/licenses
- https://choosealicense.com/
- https://www.gnu.org/licenses/license-list.html

**Comment by GrooveStomp** [comment]
I've brought this up with Tiff and Mishra.
I've broached it with the Zero team.
So far it's stalled.

Some front runners:
- Mozilla Public License v2
- Apache 2
- MIT
- GNU AGPLv3 (unlikely, but I personally like this one)

**Comment by GrooveStomp** [comment]
Dependency licenses are now tracked here: https://docs.google.com/spreadsheets/d/1tg3GVtbE7WDgrWAAwIDBq8TA0A1uCYbV1K5US9UH6AQ/edit#gid=87926421
