### ISSUE TITLE
Cron Jobs Support

### ISSUE THREAD

**Issue by dtoki** [commitdev/zero#221]
Add examples for creating a cron job using Kubernetes' cron support
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by GrooveStomp** [comment]
@bmonkman you suggested having a template of some sort since Cron jobs are already supported in Kubernetes.
Would that somehow tie in to this repo? https://github.com/commitdev/zero-deployable-backend/

**Comment by bmonkman** [comment]
Yeah exactly. It would be an example of something that would most likely be part of your backend application.
