### ISSUE TITLE
Validate zero-module.yml module before parsing

### ISSUE THREAD

**Issue by dtoki** [commitdev/zero#230]
check for required fields before parsing.

**Comment by GrooveStomp** [comment]
The way I understand this is that currently we only get an error if the yaml fails to unmarshal properly.  That could be OK, but it looks like we also have out-of-band information embedded in the field tags.

This is the complete datastructure we use:
```Go
type ModuleConfig struct {
	Name                string
	Description         string
	Author              string
	DependsOn           []string `yaml:"dependsOn,omitempty"`
	TemplateConfig      `yaml:"template"`
	RequiredCredentials []string `yaml:"requiredCredentials"`
	Parameters          []Parameter
	Conditions          []Condition `yaml:"conditions,omitempty"`
}

type Parameter struct {
	Field           string
	Label           string   `yaml:"label,omitempty"`
	Options         []string `yaml:"options,omitempty"`
	Execute         string   `yaml:"execute,omitempty"`
	Value           string   `yaml:"value,omitempty"`
	Default         string   `yaml:"default,omitempty"`
	Info            string   `yaml:"info,omitempty"`
	FieldValidation Validate `yaml:"fieldValidation,omitempty"`
}

type Condition struct {
	Action     string   `yaml:"action"`
	MatchField string   `yaml:"matchField"`
	WhenValue  string   `yaml:"whenValue"`
	Data       []string `yaml:"data,omitempty"`
}

type Validate struct {
	Type         string `yaml:"type,omitempty"`
	Value        string `yaml:"value,omitempty"`
	ErrorMessage string `yaml:"errorMessage,omitempty"`
}

type TemplateConfig struct {
	StrictMode bool
	Delimiters []string
	InputDir   string `yaml:"inputDir"`
	OutputDir  string `yaml:"outputDir"`
}
```

One of the out-of-band pieces of data appears to be:
- `omitempty` fields are optional
And it follows that:
- Any field without `omitempty` is _required_

This last part in particular has no validation currently.
I think that's the _only_ thing we don't currently catch while unmarshalling?

**Comment by GrooveStomp** [comment]
It also seems like slices implicitly allow the given attribute from the yaml.
ie., `Condition.Data` is optional since it allows 0 or more values.
It also occurs to me just now that `omitempty` is used on marshal, not unmarshal; but I think it still works for implicitly specifying whether a field is required or not?

**Comment by GrooveStomp** [comment]
I've been attempting meta-programming for this task via the reflect package, but now I'm wondering if maintaining some secondary structure/validation would be better?
