### ISSUE TITLE
Github Actions support

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#238]
First do an analysis to see if we are able to reproduce the functionality we have now on CircleCI.
If we are, look into the best way to do this in Github Actions. How much re-usable community code can we use?
Most likely a lot of stuff already exists for things like building, pushing images, AWS CLI support, kubectl support, etc.
After analysis, build this support into existing frontend/backend deployment pipelines and add support for choosing either CircleCI or GHA.

**Comment by dtoki** [comment]
### CirclCI <> GHA Feature Set Analysis


The table below outlines an overview feature-set utilization analysis between CircleCi and GitHub actions (GHA) to explore the possibility of `Zero` to offer an option to support both the later or former as a viable out of box solution for our users CI/CD


Circle Ci Feature | GitHub (GHA) Support|
:--: | :--
Aws-ecr (push to elastic container registry) | https://github.com/aws-actions/amazon-ecr-login <br/> **first party support.**
Aws-eks (interact with eks cluster) | https://github.com/marketplace/actions/eks-action <br/> **existing community support.**
Aws-s3 (sync with aws s3) | **first party support.**
Aws-cli (configure credentials) | https://github.com/aws-actions/configure-aws-credentials  <br/> **first party support.**
queue (manual approval step) | sample solution  <br/> https://www.aaron-powell.com/posts/2020-03-23-approval-workflows-with-github-actions/ <br/><br/> Github community 🧵 discussing topic: <br/> https://github.community/t/github-actions-manual-trigger-approvals/16233 <br/><br/> **some extra work needed.**
version-tag | I couldn't easily find a GHA match for our current exact workflow, but we could easily recreate our current CircleCi behaviour. Alternatively, we could change how we tag images when using GHA to be more in line with some existing community solutions & standard versioning practice. <br/><br/> We'd have to adopt semantic versioning techniques and have a VERSION file at the root of our module repos. <br/> <br/>**some extra work needed.**



List of some curated GHAs:
1. https://github.com/sdras/awesome-actions

**Comment by bmonkman** [comment]
Queue and wait for approval are separate concerns. 
Wait for approval just stops the pipeline until a user manually says it should continue.
Queueing should prevent either the entire pipeline or specific tasks from running multiple times in parallel across mulitple executions of the pipeline.
The queueing orb we are using actually isn't great, so if we could find something better on GHA that would be nice. The issue with any queueing system is that most likely it requires some (probably atomic) state management system, which isn't available as a first-party option in many build pipeline tools, especially cloud-based ones.

**Comment by bmonkman** [comment]
To reproduce the version functionality we have we would just have to find some way to get a monotonically increasing number - ideally starting from 1 per pipeline.
It was nice with Circle because we were just able to use their build id that is already exposed through an env var but actually I think this is also supported in GHA with the  `GITHUB_RUN_NUMBER` env var.

**Comment by dtoki** [comment]
> To reproduce the version functionality we have we would just have to find some way to get a monotonically increasing number - ideally starting from 1 per pipeline.
> It was nice with Circle because we were just able to use their build id that is already exposed through an env var but actually I think this is also supported in GHA with the `GITHUB_RUN_NUMBER` env var.

Right!! just read up on available envs there's the `GITHUB_SHA_SHORT ` which is exactly what we need for 1 -> 1 parity

**Comment by bmonkman** [comment]
If we use the configure aws credentials it may not be worth using that eks action, it doesn't add much aside from calling `aws eks update-kubeconfig`, so as long as the other action sets the config in such a way that we can use it in another step we should be fine. We may want to find or create an action that has some kubernetes tooling in it though (kubectl, kustomize, etc.)
Looks like that eks action uses the alpine k8s image `alpine/k8s:1.14.6`

**Comment by dtoki** [comment]
> If we use the configure aws credentials it may not be worth using that eks action, it doesn't add much aside from calling `aws eks update-kubeconfig`, so as long as the other action sets the config in such a way that we can use it in another step we should be fine. We may want to find or create an action that has some kubernetes tooling in it though (kubectl, kustomize, etc.)
> Looks like that eks action uses the alpine k8s image `alpine/k8s:1.14.6`

Right! I'd defiantly lean a bit more towards creating an action with the kubectl, etc.. tools we need bundled into one if possible. I'll poke around and see how the config is set and if it persists across steps.

**Comment by dtoki** [comment]
Implementation not possible due to GHA limitation not having an inbuilt approval step see  👇

https://github.community/t/github-actions-manual-trigger-approvals/16233
