### ISSUE TITLE
Add push notification support

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#245]
Add web + mobile push notification support.
Related to #244 as they may use the same tool / APIs
Look into the best library to use. AWS SNS may have support for what we need, but we can investigate Twilio, Pusher, etc.
Should include backend and frontend example code

**Comment by beiercai** [comment]
- Notification Infrastructure
- Push for Web
- Push for Mobile
- Client-side implementation

**Comment by beiercai** [comment]
@larrylin17 to add design/architecture here

**Comment by beiercai** [comment]
- Acceptance Criteria 
- come up with your own AC

**Comment by larrylin17** [comment]
High-level concept document
https://docs.google.com/document/d/1s-S8pbc_qSbA_FKgq4KPct7Br7LZkKXbRaVpptK6eYQ/edit#heading=h.h5kk8zpoaowg
