### ISSUE TITLE
Add VPN support

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#257]
We may have internal resources we want to access securely (databases, kibana, etc.) so a VPN would be nice to be able to get access to the VPC.
Wireguard on an EC2 instance is probably a fine place to start, maybe we can use this terraform or something similar:
https://github.com/jmhale/terraform-aws-wireguard

It would also be nice to have an internal route53 zone so we can create internal-only hostnames for things.

**Comment by sshi100** [comment]
Per discussion with Bill, we decided to take docker solution [wireguard-go-docker](https://hub.docker.com/r/masipcat/wireguard-go ) instead of EC2.

**Comment by sshi100** [comment]
Plan
- [ ] Trial on my project with temporary private key
- [ ] Use aws secret manage to store the private key and retrieve from code
- [ ] Use internal subnets of rds and kibana etc.

**Comment by sshi100** [comment]
PR: https://github.com/commitdev/zero-aws-eks-stack/pull/85

**Comment by sshi100** [comment]
Completed.
