### ISSUE TITLE
Retrofit Helix service to run inside new infrastructure

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#270]
- Check out the Dockerfile to make sure it looks good
- Add kubernetes manifests
- Update circleci pipeline with zero code. (Careful here to not break their current pipeline)

**Comment by davidcheung** [comment]
- [ ] dockerfile to build/run app
- [ ] circleci.yml

  - [ ] (generic)supporting node build 
  - [ ] (helix)supporting connecting to their empty DB for testing
  - [ ] new temp state that deploys to both their stage + new infra?
  - [ ] testing on helix service with manually injected `aws_env` using the `helix-ci-user`
