### ISSUE TITLE
helix: cloudfront signing on k8s stage 

### ISSUE THREAD

**Issue by davidcheung** [commitdev/zero#287]
- [x]  keypair setup from IAM:root to be able to sign CF keypairs
- [x] pod to have private key 
- [x] pod to have IRSA with ~CF~ /S3 access 
- [x] S3 bucket for uploads 
- [x] CF setup for signing 
- [x] s3 cors policy to allow `frontend-domain` to post(upload) to it 
- [x] CF policy to allow specifying another account_id

**Comment by davidcheung** [comment]
@bmonkman I'm running into some trouble with the CF signing, im able to get the upload to bucket 
and get backend to ***sign some sort of URL**, but when trying to access [the link](https://d3a7mpsjjtgfef.cloudfront.net/ep/33/placeholder.pdf?Expires=2074615932&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kM2E3bXBzamp0Z2ZlZi5jbG91ZGZyb250Lm5ldC9lcC8zMy9wbGFjZWhvbGRlci5wZGYiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjIwNzQ2MTU5MzJ9fX1dfQ__&Signature=kmRXb-YtxZ3MFzoQUES1kprqiN2GQ4cKBxLSRFHopXh7K-yCeQIFbv844DFmvvndoVur1fcHnmrpx0h0x19h~soFMB3TIJxCWVlEqUkJ-fHympMJ7A19PWqzVqEyTdcYoAirmRcoNx0CKH~7vkM2RFjsK6SGlimBOwl3T3e1n5KZhgwtZYeB-4O1FZ03YE5Pq4oOImBxOHXwPtwKlG1tKLP2-VS1itJYM0bUMmPh-OVBmb8dOXFBvjiCI1vY3dSANSiolqhXE~ThLnbXzU1XCniqBxRsrzdjnatwu9mIiMFqQAvPLBoOky2EYJ-QE0vRYYwoo94q8l~SDSJluNSTCw__&Key-Pair-Id=APKAJKE6G5ZZE3J2XTAQ) 


 I get an unknown key error 
```xml
<Error>
  <Code>InvalidKey</Code>
  <Message>Unknown Key</Message>
</Error>
```
**I think this is whats wrong?**
My assumption is something is misconfigure with the IAM user's, [according to docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-trusted-signers.html#private-content-verifying-trusted-signers-active) it has 2 conditions 
- AWS account need to have 1+ key pair as the signer (implies Signer is Active, not sure what that means) 
- cloudfront aware of keypair

**Findings**
Using the cli to inspect the distro i can see I have no keypair available for distro to use 
`aws cloudfront get-distribution --id E48M4YXQ44VOL | jq -r '.Distribution.ActiveTrustedSigners'`
```json
{
  "Enabled": true,
  "Quantity": 1,
  "Items": [
    {
      "AwsAccountNumber": "self",
      "KeyPairIds": {
        "Quantity": 0
      }
    }
  ]
}
```

**Comment by bmonkman** [comment]
Hmm I created a keypair in that account and ran the script to import it into secrets manager.. @GrooveStomp Any thoughts?

**Comment by GrooveStomp** [comment]
Not sure. I've been chatting with David about it and I'm not sure where my local project and Helix diverge on this front.
We'll have to investigate it more.
@davidcheung wrote this:

> the doc says theres only 2 conditions
- AWS account need to have 1+ key pair
- cloudfront aware of keypair

It's that second part that seems mysterious to me.

**Comment by bmonkman** [comment]
Yeah we are making CF aware of the keypair by saying "self" in trusted signers. One possibility if everything looks good is that it's because we have 2 aws accounts in our organization, and so instead of using "self" maybe we need to specify the other account since that one is the "master" account.

**Comment by davidcheung** [comment]
I've tried changing in Behavior's trusted signers to `117744668063` and it just saves as `Self`
