### ISSUE TITLE
Allow user of zero cli to overwrite destination files during create

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#289]
Add an `--overwrite` argument to `zero create` to allow a user to overwrite any files that already exist when templating.
Some support for this already exists in the code, as we used to support this, but it will need to be tested. (see `generate_modules.go`)

**Comment by GrooveStomp** [comment]
First run with `zero create`, then record file modification times via: `tree -D`:
[https://app.zenhub.com/files/203630543/91eeee62-354e-4fa0-ba98-81a1da23b89a/download](https://app.zenhub.com/files/203630543/91eeee62-354e-4fa0-ba98-81a1da23b89a/download)

Second run with `zero create --overwrite` and file modification times recorded via: `tree -D`:
[https://app.zenhub.com/files/203630543/6ac64bcd-693b-40d3-9e9a-baa04e562460/download](https://app.zenhub.com/files/203630543/6ac64bcd-693b-40d3-9e9a-baa04e562460/download)

Diff of the file modification times via: `diff log1.txt log2.txt --suppress-common-lines --suppress-blank-empty`
[https://app.zenhub.com/files/203630543/f622cb38-043d-4726-96db-fa08985bdbeb/download](https://app.zenhub.com/files/203630543/f622cb38-043d-4726-96db-fa08985bdbeb/download)
