### ISSUE TITLE
Wireguard secret should get cleaned up with teardown.

### ISSUE THREAD

**Issue by GrooveStomp** [commitdev/zero#293]

**Comment by sshi100** [comment]
this issue has been addressed by another fix under `teardown-secrets`:
`aws secretsmanager list-secrets --region $(AWS_DEFAULT_REGION) --query "SecretList[?Tags[?Key=='wg' && Value=='$(PROJECT)-$(ENVIRONMENT)']].[Name] | [0][0]" | xargs aws secretsmanager delete-secret --region $(AWS_DEFAULT_REGION) --secret-id || echo "Secret already removed"`
