### ISSUE TITLE
helix: allow developer role to `pods/exec` into VPN namespace in prod 

### ISSUE THREAD

**Issue by davidcheung** [commitdev/zero#305]
for developers to setup their own VPN keypair, they must exec into the VPN pod to run the `wg` command
but with the restricted access on prod they actually cant `exec` into `pods`, we may need to have a role(non-cluster-role) + binding that allows `pods/exec` into VPN namespace

Options: 
- currently we only need clusterroles, but if we want more fine grain control we may want to introduce roles too?  Perhaps looking at user_access.tf and changing roles -> clusterRole? 
```rb
k8s_developer_access = [
    {
      verbs      = ["exec", "list"]
      api_groups = [""]
      resources  = ["pods", "pods/exec", "pods/portforward"]
      }, {
      verbs      = ["get", "list", "watch"]
      api_groups = ["*"]
      resources = ["deployments", "configmaps", "pods", "pods/log", "pods/status", "jobs", "cronjobs", "services",
        "daemonsets", "endpoints", "namespaces", "events", "ingresses", "horizontalpodautoscalers", "horizontalpodautoscalers/status"
      ]
    }, {
      namespace: "vpn", # <------- maybe something like this and then it will create role instead of clusterrole
      verbs      = ["exec", "list"]
      api_groups = [""]
      resources  = ["pods", "pods/exec"]
   }
  ]
```
https://github.com/commitdev/terraform-aws-zero/blob/main/modules/user_access/main.tf#L87-L119

https://github.com/commitdev/zero-aws-eks-stack/blob/main/templates/terraform/environments/stage/user_access.tf#L165-L211

**Comment by sshi100** [comment]
Yes, we could add something alike in Zero.

**Comment by sshi100** [comment]
After a quick check on code, we need refactor this. Per current `vpn` implementation, the namespace and deployment etc. are defined in infrastructure/kubernetes side, where no roles & policies get associated. That means `vpn` pod execution can not be executed by that script when a developer is under k8s developer context.

Solution:
Move `vpn` to infrastructure/terraform side, and apply role based policies to it.

**Comment by bmonkman** [comment]
Roles and Rolebindings are application-specific and not global, so I think we shouldn't be dealing with them in the same way. 
Instead how about we allow an administrator to add users to arbitrary k8s groups, then leave it up to applications to create roles that use those groups. 
For example, we could add something like this in `environments/shared/main.tf`:
```hcl
        {
            name  = "dev1"
            roles = [
              { name = "developer", environments = ["stage", "prod"] }
            ]
            global_roles       = ["mfa-required", "console-allowed"]
            k8s_groups         = ["vpn-users"]
            create_access_keys = false
          },
```

And then in `modules/kubernetes/main.tf` we create a `Role` and a `RoleBinding` that allows access to that group:
```yaml
subjects:
- kind: Group
  name: "vpn-users"
  apiGroup: rbac.authorization.k8s.io
```

**Comment by bmonkman** [comment]
Sorry, actually this should be a per-role thing instead of per-user.
So that would mean in `terraform/environments<env>/main.tf` we would have a new field like:
```
     {
       name         = "operator"
       aws_policy   = data.aws_iam_policy_document.operator_access.json
       k8s_policies = local.k8s_operator_access             
       k8s_groups   = ["vpn-access"]
     },
```

**Comment by sshi100** [comment]
Sure, that's what we want for now.

**Comment by sshi100** [comment]
PR: https://github.com/commitdev/zero-aws-eks-stack/pull/159

**Comment by sshi100** [comment]
Completed
