### ISSUE TITLE
DB Migration

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#323]
Add a DB migration tool for services to make it easier to set up schema and seed data for projects, tests, local dev, etc.

- Should use an existing tool with a good amount of flexibility (Flyway, Liquibase, etc.) and support for typical migration workflows (stateful, with support for up/down changes, etc.)
- Must support at least MySQL and Postgres
- Must be able to run easily in multiple environments 
- Must be able to run during deployment (probably via a container in k8s
- Must be documented
- Online schema change support probably not a requirement right now. It would be nice if the tool supported it but I don't think there is a tool out there that does it for both MySQL and Postgres

**Comment by sshi100** [comment]
Done the phase I investigation and feedback collection from a few of Developers:
- different teams are using different ways, mainly per language specific tool

From DevOps point of view, generic tool like `flyway` could be integrated into Zero dev environment and CI/CD.

**Comment by sshi100** [comment]
The first trial with design:
- add migration process into k8s /migration where job with `flyway` and configmaps are defined
- add migration step into CircleCI deploy
- add migration step into dev environment

**Comment by sshi100** [comment]
Done the effort on other migration solutions, then done deeper comparison with similar tool `liquidbase`. Here there is a comparison from liquidbase point of view:  [Liquidbase vs Flyway](https://www.liquibase.org/liquibase-vs-flyway)

I would select `flyway` as the proper one for this round, considering the simplicity for startup and easy to maintain.

**Comment by bmonkman** [comment]
In what ways is Flyway simpler and easier to maintain than Liquibase?

**Comment by sshi100** [comment]
Liquibase uses one single XML in change log style to manage all the migration changes, while Flyway uses single file per migration.

**Comment by sshi100** [comment]
TODO next round:
- support S3 to overcome the limit of K8S configmap
- study on a framework to cover both generic and application specific migration tools
