### ISSUE TITLE
Create a zero static site for all resources and documentation

### ISSUE THREAD

**Issue by bmonkman** [commitdev/zero#342]
We're going to want a lot more documentation, learning resources, and rich content than we'll be able to serve in a friendly way using a markdown README on github.
Also a central landing page with a concise description of what Zero does, links to repos and docs, to our community Slack, and a nice, pretty video.
Let's think about how we can bring up a site to compile all these things in one place. 
Maybe just commit.dev/zero for now, rather than a separate domain? 
Can pull in Ashley / Anita / Paul, whoever else as necessary.

**Comment by davidcheung** [comment]
Maybe for more complex components like user-auth / logging / dev-experience / vpn / irsa 

we can have its own "component/feature overview"  in the our new site like 
```markdown
# Overview

## areas span
- eks
- backend
- frontend

## features/ What we expect you to do with it? (basically a tldr;)
- user identity database
- session creation / store
- session authentication proxy

# Details

## what we setup for them
- jwks_private_key (for oathkeeper to sign session tokens)
- database 
- kubernetes secret(connection-string to connect to kratos auth db)

## How to use? 


## Under the hood
 explain how the login flow works, which endpoints are hit to achieve what
 

## what doesn't it do?
- It does not have an admin dashboard
- 


## What is the road map for this component?
- webhook to call to your application upon signups / logins
```

**Comment by bmonkman** [comment]
I've seen this tool used a bunch for turning markdown docs into simple static doc sites: https://squidfunk.github.io/mkdocs-material/

**Comment by bmonkman** [comment]
@anikey @beiercai FYI
