### ISSUE TITLE
move ECR repo creation to shared-env

### ISSUE THREAD

**Issue by davidcheung** [commitdev/zero#408]
currently, its created in Stage, but it really is shared between both env 

https://github.com/commitdev/zero-aws-eks-stack/blob/main/templates/terraform/environments/stage/main.tf#L67

**Comment by bmonkman** [comment]
While we're at it let's also enable auto image scanning: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_repository#image_scanning_configuration

**Comment by deven96** [comment]
Hi @davidcheung 
I would like to take a stab at this. Any helpful information I'd need?
