### ISSUE TITLE
Homebrew - Warning of deprecated function

### ISSUE THREAD

**Issue by awjudd** [commitdev/zero#441]
When running a `brew update` or any other command, you receive the following warning message:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the commitdev/zero tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/commitdev/homebrew-zero/zero.rb:9
```

**Comment by bmonkman** [comment]
Thanks for reporting this. The brew formula is created by a tool we use called `goreleaser` but they have removed the use of this deprecated field in a newer version. I'll make sure to update the version I'm using and for now I'll update the formula manually to fix the current version.
