### ISSUE TITLE
ability to override or append to registry

### ISSUE THREAD

**Issue by davidcheung** [commitdev/zero#469]
Problem: 
Currently registry is hardcoded, the struct is very simple right now 
https://github.com/commitdev/zero/blob/587d6f575532f5cdc1c5e6796ac4e8aab5ce78f5/internal/registry/registry.go#L3-L7
that means to build a module u must also build your own zero binary. 

Potential solution: 
Maybe we can allow something like ~/.zero-registry.yaml, we can just add some annotations to the struct and  parse the config, allowing users to customize registry for their own use

**Comment by JeanPinzon** [comment]
Working on it

**Comment by JeanPinzon** [comment]
Hey everyone! I created the PR #470 trying to solve it. Please let me know if I should change anything. Thanks!

**Comment by bmonkman** [comment]
PR merged and v0.2.5 released: https://github.com/commitdev/zero/releases/tag/v0.2.5
Thanks again!
